### PR TITLE
Exclude id's from Excerpt api

### PR DESCRIPTION
**Pull request by EdwinP7**
whatever

### CODE REVIEW

**Review by sergioavila2720 — CHANGES_REQUESTED** [review]
hmmm doesn't look good

**Comment by EdwinP7** [comment]
> hmmm doesn't look good

dafuq u mean?

**Comment by sergioavila2720** [comment]
Why'd you merge!?

**Comment by EdwinP7** [comment]
> Why'd you merge!?

I don't take orders from you

**Pull request merged**
